[build]
  base = "template3byberru"
  publish = "template3byberru"
  command = ""

[context.production.environment]
  NODE_VERSION = "18" # Optionnel, au cas où tu utilises un outil node (vite, etc.)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
